### ISSUE TITLE
How do I run this code in React?

### ISSUE THREAD

**Issue by W00been** [spatialillusions/milsymbol-generator#20]
I am a beginner developer.
How do I run this code in React?

**Comment by Plavit** [comment]
Hi. To put it simply - you do not. It is built by nodeJS, no React included.

To deploy locally, after downloading this repository, all that is needed is to run `npm install` in the root folder and then run `npm run build`. No errors should come up, only warnings. After this, all it takes is to open `unitgenerator/index.html` in (almost) any browser.

Hope this helps 🙂
